#ifndef PAGES_COMMON_H
#define PAGES_COMMON_H

// Qt 标准头文件
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QStackedWidget>
#include <QScrollArea>
#include <QLabel>
#include <QPushButton>
#include <QToolButton>
#include <QFrame>
#include <QMessageBox>
#include <QTableWidget>
#include <QHeaderView>
#include <QComboBox>
#include <QLineEdit>
#include <QTextEdit>
#include <QGroupBox>
#include <QFormLayout>
#include <QTabWidget>
#include <QDialog>
#include <QDialogButtonBox>
#include <QSpinBox>
#include <QDateTimeEdit>
#include <QDateEdit>
#include <QInputDialog>
#include <QCheckBox>
#include <QButtonGroup>
#include <QRadioButton>
#include <QTreeWidget>
#include <QTreeWidgetItem>
#include <QToolTip>
#include <QFileDialog>
#include <QFile>
#include <QTextStream>
#include <QVariantAnimation>
#include <QTransform>
#include <QPainterPath>
#include <QMouseEvent>
#include <QPropertyAnimation>
#include <QGraphicsOpacityEffect>
#include <QImage>
#include <QPainter>
#include <QIcon>
#include <QTimer>
#include <QApplication>
#include <QMenu>
#include <QAction>
#include <QGridLayout>
#include <QRegularExpression>

// 项目通用头文件
#include "PaginationBar.h"
#include "services/AuthService.h"
#include "services/AIService.h"
#include "utils/Utils.h"
#include "ui_kit/UiKit.h"
#include "ui_kit/AuthHelpers.h"
#include "ui_kit/DbHelpers.h"
#include "dialogs/ChangePasswordDialog.h"
#include "dialogs/ProfileDialog.h"
#include "dialogs/WorkOrderDetailDialog.h"

// 标准库
#include <functional>
#include <memory>

#endif // PAGES_COMMON_H
